const data = {
  products: [
    {
      _id: '1',
      name: 'paper',
      image: '/images/p1.jpg',
      price: 2,
      countInStock: 10,
      brand: 'Tesco',
      description: 'Good for Writing',
    },
    {
      _id: '2',
      name: 'Beer',
      image: '/images/p2.jpg',
      price: 3,
      countInStock: 20,
      brand: 'My Own',
      description: 'Mmmm Beer',
    },
    {
      _id: '3',
      name: 'Pen',
      image: '/images/p3.jpg',
      price: 1.5,
      countInStock: 0,
      brand: 'Berol',
      description: 'Great for Writing',
    },
    {
      _id: '4',
      name: 'Car',
      image: '/images/p4.jpg',
      price: 2500,
      countInStock: 15,
      brand: 'Vauxhall',
      description: 'Good for for driving',
    },
    {
      _id: '5',
      name: 'Xbox Series X',
      image: '/images/p5.jpg',
      price: 260,
      countInStock: 5,
      brand: 'Microsoft',
      description: 'Great for gaming',
    },
    {
      _id: '6',
      name: 'Playstation 5',
      image: '/images/p6.jpg',
      price: 200,
      countInStock: 12,
      brand: 'Sony',
      description: 'great for gaming',
    },
    {
      _id: '7',
      name: 'Nintendo Switch',
      image: '/images/p7.jpg',
      price: 299,
      countInStock: 8,
      brand: 'Nintendo',
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Fish Tank',
      image: '/images/p8.jpg',
      price: 139,
      countInStock: 2,
      brand: 'Aqua One',
      description: 'Great for stress',
    },
    {
      _id: '9',
      name: 'Pandora Bracelet',
      image: '/images/p9.jpg',
      price: 100,
      countInStock: 8,
      brand: 'Pandora',
      description: 'Great for when you have annoyed your partner',
    },
    {
      _id: '10',
      name: 'Nappies',
      image: '/images/p10.jpg',
      price: 5,
      countInStock: 12,
      brand: 'Huggies',
      description: 'A must for babies',
    },
    {
      _id: '11',
      name: 'Bed',
      image: '/images/p11.jpg',
      price: 139,
      countInStock: 4,
      brand: 'Silent Night',
      description: 'Great after a coding session',
    },
    {
      _id: '12',
      name: 'Football',
      image: '/images/p12.jpg',
      price: 10,
      countInStock: 1,
      brand: 'Adidas',
      description: 'Great for the park',
    },
    {
      _id: '143',
      name: 'Regulators',
      image: '/images/p13.jpg',
      price: 139,
      countInStock: 5,
      brand: 'Atomic',
      description: 'If you need to breathe underwater',
    },
    {
      _id: '14',
      name: 'Drone',
      image: '/images/p14.jpg',
      price: 500,
      countInStock: 7,
      brand: 'DJI',
      description: 'Great toy for the adults',
    },
  ],
}
export default data
